### ISSUE TITLE
Changes required on Readme.

### ISSUE THREAD

**Issue by Yolinda** [w3shivers/ascii-next-gen#2]
### ToDo
- [x]  Version should please change to 0.9.0, as this is well known as a beta release.
- [x] Python requirement is 3.11+.
- [x]  Project overview should for know not mention animation as we should add that later, when we are ready with the animation.
- [x] Not sure if we should add tech used as the top already indicates that we use Python. However if you still think it is important then we should probably rather mention the pip packages used in the requirements.txt file.
- [x] Your Links at the top should link to master branch as the previous branch has already been deleted.
- [x] Also on the link the Tech used is not there, but you have a double contributors link there as well. Thus I think one just needs to be renamed.
- [x] Consider adding something similar to the Getting started I have on the following [readme](https://github.com/w3shivers/text-based-game-creator).
- [x] Then please give me a short about that I can add to the repo's about section please.
- [x] The features I think you will know what to do once you played with it a bit. Thus please remember to update this section as well.

### Suggestions
- [ ] We could maybe extend the Contribution section a but by telling others how they can be part of it.
- [ ] We can also consider adding the change log to the Readme with a link to it similar to the License.

**Comment by Yolinda** [comment]
@w3shivers - below is the description that you can use for the repo

A command-line tool that can be used to convert images into **ASCII Art**. Loaded with options to customize the way in which the image is converted to ASCII Art.
